#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 14 13:41:33 2017

@author: elizabethsizemore
"""

from numpy import exp,linspace
from pylab import plot, show, xlabel,ylabel


def f(x):
    return (exp(x**2))
    

Y=[]
X=linspace(0,3,31,endpoint=True)

def frange(A,B,jump):
    while A<B:
        yield A
        A += jump
        
    
for x in frange(0.0,3.1,0.1):
    a=0.0
    b=x
    N=100
    h=(b-a)/N
    
    s=0.5*f(a) +0.5*f(b)
    for j in range(1,N):
        s += f(a+j*h)
    E_x= s*h
    
    Y.append(E_x)
    
    
print (Y)

        

plot(X,Y)
xlabel('x')
ylabel('E_x')
show()

